# Generated by Django 3.1.4 on 2020-12-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
